# Generated by Django 4.0.2 on 2022-02-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artgo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sentenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentenca', models.CharField(max_length=1200)),
                ('FkArtigoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artigoSentenca', to='pnlPdf.artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Palavra', models.CharField(max_length=200)),
                ('FKArtigoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artigoPalavra', to='pnlPdf.artigo')),
            ],
        ),
    ]
