# Generated by Django 4.0.2 on 2022-02-03 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pnlPdf', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='Artgo',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='artigo',
            name='assunto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='dispositivo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='processo',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='responsavel',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='palavra',
            name='Palavra',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Sentenca',
        ),
    ]
