# Generated by Django 4.0.2 on 2022-02-03 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pnlPdf', '0004_rename_artgo_artigo_nome_artigo_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='interesado',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='relator',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
